name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: yarn install
      run: |
        yarn install
      
    - name: yarn build
      run: |
        yarn build:all --if-present

    - name: change directory to dist
      run: |
        cd dist

    - name: initialize dist folder as git repo
      run: |
        git init

    - name: add Heroku remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

    - name: deploy to Heroku
      run: |
        git push heroku HEAD:master -f